version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      REDIS_ADDR: redis:6379
      TOKEN_RATE_LIMIT: 3
      IP_RATE_LIMIT: 5
      TOKENS_PERMITED: AAAAA|BBBBB
      EXPIRATION_TIME: 30 # Seconds